 [STACK(OWN)] [STACK(OTHER)] [HEAP] [MMAP] [SHM] [CODE] [BSS] [NULL] [RO] [WO] [RW] [EX] [INV] [INAC] [UNK]
#0  0x00007ffff.* in ► __pthread_kill_implementation \(threadid="<optimized out>", signo="6", no_tid="0"\) at pthread_kill.c:44
    Kernel Signal Handler: Signal 6 \(SIGABRT\), code -6 \(SI_TKILL\) \(\)
#1  0x00007ffff.* in __pthread_kill_internal \(signo="6", threadid="<optimized out>"\) at pthread_kill.c:78
#2  0x00007ffff.* in __GI_raise \(sig="6"\) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff.* in __GI_abort \(\) at abort.c:79
#4  0x00007ffff.* in __libc_message \(action="do_abort", fmt="0x7ffff.*"\) at ../sysdeps/posix/libc_fatal.c:155
#5  0x00007ffff.* in malloc_printerr \(str="0x7ffff.* \\".*\\""\) at malloc.c:[0-9]*
#6  0x00007ffff.* in .* at malloc.c:[0-9]*
#7  0x00007ffff.* in __GI___libc_free \(mem="<optimized out>"\) at malloc.c:[0-9]*
#8  0x000000000.* in rabbit<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*"\) at ftree.cxx:86
#9  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="0"\) at ftree.cxx:94
#10 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="1"\) at ftree.cxx:96
#11 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="2"\) at ftree.cxx:96
#12 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="3"\) at ftree.cxx:96
#13 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="4"\) at ftree.cxx:96
#14 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="5"\) at ftree.cxx:96
#15 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="6"\) at ftree.cxx:96
#16 0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t="0x0", x="0x7fffffff.*", level="7"\) at ftree.cxx:96
#17 0x000000000.* in main \(argc="1", argv="0x7fffffff.*"\) at ftree.cxx:146
#18 0x00007ffff.* in __libc_start_call_main \(main="0x4.* <main\(int, char const\*\*\)>", argc="1", argv="0x7fffffff.*"\) at ../sysdeps/nptl/libc_start_call_main.h:58
#19 0x00007ffff.* in __libc_start_main_impl \(main="0x4.* <main\(int, char const\*\*\)>", argc="1", argv="0x7fffffff.*", init="<optimized out>", fini="<optimized out>", rtld_fini="<optimized out>", stack_end="0x7fffffff.*"\) at ../csu/libc-start.c:[0-9]*
#20 0x000000000.* in _start \(\) at ../sysdeps/x86_64/start.S:[0-9]*

Exiting vdb...
