 [STACK(OWN)] [STACK(OTHER)] [HEAP] [MMAP] [SHM] [CODE] [BSS] [NULL] [RO] [WO] [RW] [EX] [INV] [INAC] [UNK]
#0  0x00007ffff78a9c99 in ► free () at /lib64/libc.so.6
    Kernel Signal Handler: Signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) trying to access 0x7ffffc000000 ()
#1  0x000000000.* in rabbit<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*\) at ftree.cxx:87
#2  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=0\) at ftree.cxx:95
#3  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=1\) at ftree.cxx:97
#4  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=2\) at ftree.cxx:97
#5  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=3\) at ftree.cxx:97
#6  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=4\) at ftree.cxx:97
#7  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=5\) at ftree.cxx:97
#8  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=6\) at ftree.cxx:97
#9  0x000000000.* in hole<node, std::map<int, int, std::less<int>, std::allocator<std::pair<int const, int> > > > \(t=0x0, x=0x7fffffff.*, level=7\) at ftree.cxx:97
#10 0x000000000.* in main \(argc=1, argv=0x7fffffff.*\) at ftree.cxx:147
#11 0x00007ffff.* in __libc_start_call_main \(.*\) at .*libc.*
#12 0x00007ffff.* in __libc_start_main_impl \(.*\) at .*libc.*
#13 0x000000000.* in _start \(\) at ../sysdeps/x86_64/start.S:[0-9]*

Lazy typedef loading is disabled. To manually load typedefs for shortening, do vdb load shorten


Exiting vdb...
