Instructions in range 0x4.* - 0x4.* of main\(int, char const\*\*\)\( argc@0x7f.*\[-0x.*\(%rbp\)\] = 1, argv@0x7ff.*\[-0x.*\(%rbp\)\] = 0x7ff.*\) *
 Mar Address            H  Offset   Ju Bytes                   Mnemo Args                  Reference                                                                                                                Target
     0x0000000000401196 6  <+0 >:      55                      push  %rbp                  %=@0x7fffffffd100
     0x0000000000401197 5  <+1 >:      48 89 e5                mov   %rsp,%rbp             
     0x000000000040119a 4  <+4 >:      53                      push  %rbx                  
     0x000000000040119b 3  <+5 >:      48 83 ec 48             sub   $0x48,%rsp            
     0x000000000040119f 2  <+9 >:      89 7d bc                mov   %edi,-0x44(%rbp)      %=0x1,argc@-0x44(%rbp)
     0x00000000004011a2 1  <+12>:      48 89 75 b0             mov   %rsi,-0x50(%rbp)      %=@0x7fffffffd218,argv@-0x50(%rbp)
  →  0x00000000004011a6 0  <+16>:      48 8d 45 c0             lea   -0x40(%rbp),%rax      s@-0x40(%rbp),s@@0x7fffffffd0c0
     0x00000000004011aa    <+20>:      48 89 c7                mov   %rax,%rdi             %=@0x7fffffffd0c0
     0x00000000004011ad    <+23>:      e8 a2 02 00 00          call  0x401454              std::string::basic_string()@%=@0x00401454
     0x00000000004011b2    <+28>:      48 c7 45 e8 00 43 40 00 movq  $0x404300,-0x18(%rbp) vm@%=@0x00404300,vmbase@-0x18(%rbp),vmbase@@0x7fffffffd0e8
     0x00000000004011ba    <+36>:      be 04 20 40 00          mov   $0x402004,%esi        %=@0x00402004 → [16]'(void*)vmbase = '
     0x00000000004011bf    <+41>:      bf c0 40 40 00          mov   $0x4040c0,%edi        std::cout@GLIBCXX_3.4%=@0x004040c0
     0x00000000004011c4    <+46>:      e8 97 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x00000000004011c9    <+51>:      48 89 c2                mov   %rax,%rdx             
     0x00000000004011cc    <+54>:      48 8b 45 e8             mov   -0x18(%rbp),%rax      vmbase@-0x18(%rbp),vmbase@@0x7fffffffd0e8,vmbase@=@0x7ffff78a953a
     0x00000000004011d0    <+58>:      48 89 c6                mov   %rax,%rsi             __GI___libc_malloc@%=@0x7ffff78a953a
     0x00000000004011d3    <+61>:      48 89 d7                mov   %rdx,%rdi             
     0x00000000004011d6    <+64>:      e8 55 fe ff ff          call  0x401030              std::ostream::operator<<(void const*)@plt%=@0x00401030
     0x00000000004011db    <+69>:      be 15 20 40 00          mov   $0x402015,%esi        %=@0x00402015 → [1]'\n'
     0x00000000004011e0    <+74>:      48 89 c7                mov   %rax,%rdi             
     0x00000000004011e3    <+77>:      e8 78 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x00000000004011e8    <+82>:      48 c7 45 e0 14 43 40 00 movq  $0x404314,-0x20(%rbp) vm@%=@0x00404314 → [1]'C',c@-0x20(%rbp),c@@0x7fffffffd0e0
     0x00000000004011f0    <+90>:      be 17 20 40 00          mov   $0x402017,%esi        %=@0x00402017 → [11]'(void*)c = '
     0x00000000004011f5    <+95>:      bf c0 40 40 00          mov   $0x4040c0,%edi        std::cout@GLIBCXX_3.4%=@0x004040c0
     0x00000000004011fa    <+100>:     e8 61 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x00000000004011ff    <+105>:     48 89 c2                mov   %rax,%rdx             
     0x0000000000401202    <+108>:     48 8b 45 e0             mov   -0x20(%rbp),%rax      c@-0x20(%rbp),c@@0x7fffffffd0e0,c@=0x0
     0x0000000000401206    <+112>:     48 89 c6                mov   %rax,%rsi             %=0x0
     0x0000000000401209    <+115>:     48 89 d7                mov   %rdx,%rdi             
     0x000000000040120c    <+118>:     e8 1f fe ff ff          call  0x401030              std::ostream::operator<<(void const*)@plt%=@0x00401030
     0x0000000000401211    <+123>:     be 15 20 40 00          mov   $0x402015,%esi        %=@0x00402015 → [1]'\n'
     0x0000000000401216    <+128>:     48 89 c7                mov   %rax,%rdi             
     0x0000000000401219    <+131>:     e8 42 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x000000000040121e    <+136>:     be 23 20 40 00          mov   $0x402023,%esi        %=@0x00402023 → [20]'(void*)(c-vmbase) = '
     0x0000000000401223    <+141>:     bf c0 40 40 00          mov   $0x4040c0,%edi        std::cout@GLIBCXX_3.4%=@0x004040c0
     0x0000000000401228    <+146>:     e8 33 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x000000000040122d    <+151>:     48 89 c2                mov   %rax,%rdx             
     0x0000000000401230    <+154>:     48 8b 45 e0             mov   -0x20(%rbp),%rax      c@-0x20(%rbp),c@@0x7fffffffd0e0,c@=0x0
     0x0000000000401234    <+158>:     48 2b 45 e8             sub   -0x18(%rbp),%rax      vmbase@-0x18(%rbp),vmbase@@0x7fffffffd0e8,vmbase@=@0x7ffff78a953a
                                                                                           %=0xffff800008756ac6
     0x0000000000401238    <+162>:     48 89 c6                mov   %rax,%rsi             %=0xffff800008756ac6
     0x000000000040123b    <+165>:     48 89 d7                mov   %rdx,%rdi             
     0x000000000040123e    <+168>:     e8 ed fd ff ff          call  0x401030              std::ostream::operator<<(void const*)@plt%=@0x00401030
     0x0000000000401243    <+173>:     be 15 20 40 00          mov   $0x402015,%esi        %=@0x00402015 → [1]'\n'
     0x0000000000401248    <+178>:     48 89 c7                mov   %rax,%rdi             
     0x000000000040124b    <+181>:     e8 10 fe ff ff          call  0x401060              std::ostream&std::operator<< <std::char_traits<char> >(std::ostream&, char const*)@plt%=@0x00401060
     0x0000000000401250    <+186>:     48 8d 45 c0             lea   -0x40(%rbp),%rax      s@-0x40(%rbp),s@@0x7fffffffd0c0
     0x0000000000401254    <+190>:     48 89 c7                mov   %rax,%rdi             %=@0x7fffffffd0c0
     0x0000000000401257    <+193>:     e8 1a 07 00 00          call  0x401976              std::string::~basic_string()@%=@0x00401976
     0x000000000040125c    <+198>:     b8 00 00 00 00          mov   $0x0,%eax             %=0x0
     0x0000000000401261    <+203>:  ╭◄ eb 1a                   jmp   0x40127d              main(int,char const**)+231@%=@0x0040127d
 Mar Address            H  Offset   Ju Bytes                   Mnemo Args                  Reference                                                                                                                Target
     0x0000000000401263    <+205>:  │  48 89 c3                mov   %rax,%rbx             
     0x0000000000401266    <+208>:  │  48 8d 45 c0             lea   -0x40(%rbp),%rax      
     0x000000000040126a    <+212>:  │  48 89 c7                mov   %rax,%rdi             
     0x000000000040126d    <+215>:  │  e8 04 07 00 00          call  0x401976              ,0x401976 <std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()>             TGT:<std::__cxx11::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string()>
     0x0000000000401272    <+220>:  │  48 89 d8                mov   %rbx,%rax             
     0x0000000000401275    <+223>:  │  48 89 c7                mov   %rax,%rdi             
     0x0000000000401278    <+226>:  │  e8 13 fe ff ff          call  0x401090              ,0x401090 <_Unwind_Resume@plt>                                                                                           TGT:<_Unwind_Resume@plt>
     0x000000000040127d    <+231>:  ╰► 48 8b 5d f8             mov   -0x8(%rbp),%rbx       @0x7fffffffd0f8,=@0x7fffffffd218
     0x0000000000401281    <+235>:     c9                      leave                       
     0x0000000000401282    <+236>:     c3                      ret                         
Lazy typedef loading is disabled. To manually load typedefs for shortening, do vdb load shorten


Exiting vdb...
