[  0-  7] int (**)(void) morev::_vptr.morev
[  8- 15]       uint32_t morev::y
[ 16- 17]       uint16_t morev::p
[ 18- 18]           char morev::u
[ 19- 19]                <unused>
[ 20- 20]           char morev::small::c
[ 21- 21]                <unused>
[ 22- 23]       uint16_t morev::small::x
[ 24- 24]           char morev::small::h
[ 25- 31]                <unused>
[ 32- 39]       uint32_t morev::big::n
[ 40- 43]            int morev::innerst::i
[ 44- 47]                <unused>
[ 48- 55]         double morev::innerst::po
[  0-  7] int (**)(void) f3::f2<X<43, 42> >::f1::f0::_vptr.f0
[  8-  8]           char f3::f2<X<43, 42> >::f1::f0::c
[  9- 11]                <unused>
[ 12- 15]   unsigned int f3::f2<X<43, 42> >::f1::f0::x
[ 16- 16]           char f3::f2<X<43, 42> >::f1::c
[ 17- 19]                <unused>
[ 20- 23]   unsigned int f3::f2<X<43, 42> >::f1::x
[ 24- 31] int (**)(void) f3::f2<X<43, 42> >::f0::_vptr.f0
[ 32- 32]           char f3::f2<X<43, 42> >::f0::c
[ 33- 35]                <unused>
[ 36- 39]   unsigned int f3::f2<X<43, 42> >::f0::x
[ 40- 40]           char f3::f2<X<43, 42> >::c
[ 41- 43]                <unused>
[ 44- 47]   unsigned int f3::f2<X<43, 42> >::x
[ 48- 48]           char f3::f2<X<43, 42> >::o
[ 49- 51]                <unused>
[ 52- 55]            int f3::m
[  0-  3]    int u::x
[  4-  7]        <unused>
[  8- 11]    int u::n.a
[ 12- 15] double u::n.b
[  0-  7] int (**)(void) oax::_vptr.oax
[  8- 11]            int oax::b0::x0
[ 12- 12]           char oax::b0::c0
[ 13- 15]                <unused>
[ 16- 19]            int oax::g0::x0
[ 20- 20]           char oax::g0::c0
[ 21- 23]                <unused>
[ 24- 31]       uint32_t oax::g0::g0
[ 32- 35]            int oax::b00::x00
[ 36- 36]           char oax::b00::c00
[ 37- 39]                <unused>
[ 40- 43]            int oax::g00::x00
[ 44- 44]           char oax::g00::c00
[ 45- 47]                <unused>
[ 48- 55]       uint32_t oax::g00::g00
[  0-  7] int (**)(void) xv::_vptr.xv
[  8- 11]            int xv::b00::x00
[ 12- 12]           char xv::b00::c00
[ 13- 15]                <unused>
[ 16- 19]            int xv::b0::x0
[ 20- 20]           char xv::b0::c0
[ 21- 23]                <unused>
[ 24- 27]            int xv::g0::x0
[ 28- 28]           char xv::g0::c0
[ 29- 31]                <unused>
[ 32- 39]       uint32_t xv::g0::g0
Exiting vdb...
