Breakpoint 2 at 0x7ffff7.*: file printf.c, line 28.
Continuing.

Breakpoint 2, __printf (format=0x402010 "%d") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402010 "%d", 1)
Continuing.

Breakpoint 2, __printf (format=0x402013 "%ld") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402013 "%ld", 2)
Continuing.

Breakpoint 2, __printf (format=0x402017 "%u") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402017 "%u", 3)
Continuing.

Breakpoint 2, __printf (format=0x40201a "%lu") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x40201a "%lu", 4)
Continuing.

Breakpoint 2, __printf (format=0x40201e "%g") at printf.c:28
.*
Waiting...
Executed vdb-va-wait-max-instructions (24) instructions but still the va_list members did not all change. We may need a higher value or did miss the right point, check manually
Using gp_offset=16, fp_offset=48
Possible function call(s):
__printf( 0x40201e "%g", 5)
Continuing.

Breakpoint 2, __printf (format=0x402021 "%f") at printf.c:28
.*
Waiting...
Executed vdb-va-wait-max-instructions (24) instructions but still the va_list members did not all change. We may need a higher value or did miss the right point, check manually
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402021 "%f", 6)
Continuing.

Breakpoint 2, __printf (format=0x402024 "%lf") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402024 "%lf", 7)
Continuing.

Breakpoint 2, __printf (format=0x402034 "%s") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402034 "%s", 0x402028 "Hello World")
Continuing.

Breakpoint 2, __printf (format=0x402037 "%p") at printf.c:28
.*
Waiting...
va_list completely updated, va extraction has a higher chance of working now
fp_offset did not update. Please single step (at the risk of clobbering fixed parameters) or inspect disasembly yourself to figure out a proper value
Using gp_offset=8, fp_offset=48
Possible function call(s):
__printf( 0x402037 "%p", 0x0000000000401136 <main(int, char const**)> →   push %rbp ? )
Exiting vdb...
